//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This Persona.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Per Kilometer.
        /// </summary>
        public static string AgePerKilometer {
            get {
                return ResourceManager.GetString("AgePerKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Gear.
        /// </summary>
        public static string AutomaticGear {
            get {
                return ResourceManager.GetString("AutomaticGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Got Hit.
        /// </summary>
        public static string BackGotHit {
            get {
                return ResourceManager.GetString("BackGotHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Got Hit Front Painted.
        /// </summary>
        public static string BackGotHitFrontPainted {
            get {
                return ResourceManager.GetString("BackGotHitFrontPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Painted.
        /// </summary>
        public static string BackPainted {
            get {
                return ResourceManager.GetString("BackPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Got Hit.
        /// </summary>
        public static string BothGotHit {
            get {
                return ResourceManager.GetString("BothGotHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Healthy.
        /// </summary>
        public static string BothHealthy {
            get {
                return ResourceManager.GetString("BothHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Painted.
        /// </summary>
        public static string BothPainted {
            get {
                return ResourceManager.GetString("BothPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands&apos; Models.
        /// </summary>
        public static string BrandSubModels {
            get {
                return ResourceManager.GetString("BrandSubModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Type.
        /// </summary>
        public static string BrandType {
            get {
                return ResourceManager.GetString("BrandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Willing To Exchange.
        /// </summary>
        public static string CanBeExchanged {
            get {
                return ResourceManager.GetString("CanBeExchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Body Status.
        /// </summary>
        public static string CarBodyStatus {
            get {
                return ResourceManager.GetString("CarBodyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Brand.
        /// </summary>
        public static string CarBrand {
            get {
                return ResourceManager.GetString("CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis&apos; Status.
        /// </summary>
        public static string CarChassisStatus {
            get {
                return ResourceManager.GetString("CarChassisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearboxs&apos; Status.
        /// </summary>
        public static string CarGearBoxStatus {
            get {
                return ResourceManager.GetString("CarGearBoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Time Remained.
        /// </summary>
        public static string CarInsuranceTimeRemained {
            get {
                return ResourceManager.GetString("CarInsuranceTimeRemained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Creation Year.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors&apos; Status.
        /// </summary>
        public static string CarMotorStatus {
            get {
                return ResourceManager.GetString("CarMotorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        public static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored Smoothing.
        /// </summary>
        public static string ColoredSmoothing {
            get {
                return ResourceManager.GetString("ColoredSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorless Smoothing.
        /// </summary>
        public static string ColorLessSmoothing {
            get {
                return ResourceManager.GetString("ColorLessSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely Painted.
        /// </summary>
        public static string CompletelyPainted {
            get {
                return ResourceManager.GetString("CompletelyPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Brand.
        /// </summary>
        public static string ComputerBrand {
            get {
                return ResourceManager.GetString("ComputerBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Year.
        /// </summary>
        public static string ConstructionYear {
            get {
                return ResourceManager.GetString("ConstructionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashed.
        /// </summary>
        public static string Crashed {
            get {
                return ResourceManager.GetString("Crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight Months.
        /// </summary>
        public static string EightMonths {
            get {
                return ResourceManager.GetString("EightMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven Months.
        /// </summary>
        public static string ElevenMonths {
            get {
                return ResourceManager.GetString("ElevenMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Family or a Single Man\Woman.
        /// </summary>
        public static string FamilyOrSingle {
            get {
                return ResourceManager.GetString("FamilyOrSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Months.
        /// </summary>
        public static string FiveMonths {
            get {
                return ResourceManager.GetString("FiveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Number.
        /// </summary>
        public static string FloorNumber {
            get {
                return ResourceManager.GetString("FloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Months.
        /// </summary>
        public static string FourMonths {
            get {
                return ResourceManager.GetString("FourMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Got Hit.
        /// </summary>
        public static string FrontGotHit {
            get {
                return ResourceManager.GetString("FrontGotHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Got Hit Back Painted.
        /// </summary>
        public static string FrontGotHitBackPainted {
            get {
                return ResourceManager.GetString("FrontGotHitBackPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Painted.
        /// </summary>
        public static string FrontPainted {
            get {
                return ResourceManager.GetString("FrontPainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Good As New.
        /// </summary>
        public static string GoodAsNew {
            get {
                return ResourceManager.GetString("GoodAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has a Cellar?.
        /// </summary>
        public static string HasCellar {
            get {
                return ResourceManager.GetString("HasCellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has an Elevator?.
        /// </summary>
        public static string HasElevator {
            get {
                return ResourceManager.GetString("HasElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has a Parking?.
        /// </summary>
        public static string HasParking {
            get {
                return ResourceManager.GetString("HasParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string Healthy {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Type.
        /// </summary>
        public static string HouseType {
            get {
                return ResourceManager.GetString("HouseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Identity.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date Time.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mansion.
        /// </summary>
        public static string Mansion {
            get {
                return ResourceManager.GetString("Mansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Gear.
        /// </summary>
        public static string ManualGear {
            get {
                return ResourceManager.GetString("ManualGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Size.
        /// </summary>
        public static string MemorySize {
            get {
                return ResourceManager.GetString("MemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meterage.
        /// </summary>
        public static string Meterage {
            get {
                return ResourceManager.GetString("Meterage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Scratches.
        /// </summary>
        public static string MinorScratches {
            get {
                return ResourceManager.GetString("MinorScratches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Brand.
        /// </summary>
        public static string MobileBrand {
            get {
                return ResourceManager.GetString("MobileBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Rent.
        /// </summary>
        public static string MonthlyRent {
            get {
                return ResourceManager.GetString("MonthlyRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need For Repair.
        /// </summary>
        public static string NeedForRepair {
            get {
                return ResourceManager.GetString("NeedForRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine Months.
        /// </summary>
        public static string NineMonths {
            get {
                return ResourceManager.GetString("NineMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scratches.
        /// </summary>
        public static string NoScratches {
            get {
                return ResourceManager.GetString("NoScratches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Floors.
        /// </summary>
        public static string NumberOfFloors {
            get {
                return ResourceManager.GetString("NumberOfFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Rooms.
        /// </summary>
        public static string NumberOfRooms {
            get {
                return ResourceManager.GetString("NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Brand.
        /// </summary>
        public static string ObjectBrand {
            get {
                return ResourceManager.GetString("ObjectBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Month.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted.
        /// </summary>
        public static string Painted {
            get {
                return ResourceManager.GetString("Painted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Meter.
        /// </summary>
        public static string PricePerMeter {
            get {
                return ResourceManager.GetString("PricePerMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions.
        /// </summary>
        public static string Professions {
            get {
                return ResourceManager.GetString("Professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string Scrap {
            get {
                return ResourceManager.GetString("Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string ScreenSize {
            get {
                return ResourceManager.GetString("ScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondHand.
        /// </summary>
        public static string SecondHand {
            get {
                return ResourceManager.GetString("SecondHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Range.
        /// </summary>
        public static string ServiceRange {
            get {
                return ResourceManager.GetString("ServiceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Months.
        /// </summary>
        public static string SevenMonths {
            get {
                return ResourceManager.GetString("SevenMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve Months.
        /// </summary>
        public static string SixMonths {
            get {
                return ResourceManager.GetString("SixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategories.
        /// </summary>
        public static string SubCategories {
            get {
                return ResourceManager.GetString("SubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitable For:.
        /// </summary>
        public static string SuitableFor {
            get {
                return ResourceManager.GetString("SuitableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten Months.
        /// </summary>
        public static string TenMonths {
            get {
                return ResourceManager.GetString("TenMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Months.
        /// </summary>
        public static string ThreeMonths {
            get {
                return ResourceManager.GetString("ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Of Experience.
        /// </summary>
        public static string TimeOfExperience {
            get {
                return ResourceManager.GetString("TimeOfExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve Months.
        /// </summary>
        public static string TwelveMonths {
            get {
                return ResourceManager.GetString("TwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Months.
        /// </summary>
        public static string TwoMonths {
            get {
                return ResourceManager.GetString("TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date Time.
        /// </summary>
        public static string UpdateDateTime {
            get {
                return ResourceManager.GetString("UpdateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Price.
        /// </summary>
        public static string WholePrice {
            get {
                return ResourceManager.GetString("WholePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
    }
}
